### ISSUE TITLE
Do you have a complete demo?

### ISSUE THREAD

**Issue by shizu2014** [paulhuggett/machowriter#1]
Do you have a complete demo? It seems that this program doesn't know what to do.

**Comment by paulhuggett** [comment]
No, nothing like a demo. However, it's an extremely simple program at the moment: just run it with a output path as the sole positional argument. It will write a valid MachO binary to that path. If you run that binary it will execute successfully but do nothing.

I'm intending to extend the library to make it possible to write more interesting programs.
